apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
#  name: cluster1
  name: mt-pxctest-scheduler
#  finalizers:
#    - delete-pxc-pods-in-order
spec:
  crVersion: 1.13.0
  secretsName: cluster1-secrets
  allowUnsafeConfigurations: false
  updateStrategy: SmartUpdate
  upgradeOptions:
    versionServiceEndpoint: https://check.percona.com
    apply: disabled
    schedule: "0 4 * * *"
  pxc:
    size: 3
    image: percona/percona-xtradb-cluster:8.0.31-23.2 
    autoRecovery: true
    expose:
      enabled: true
      type: ClusterIP
    readinessDelaySec: 15
    livenessDelaySec: 600
    readinessProbes:
      timeoutSeconds: 600
    livenessProbes:
      timeoutSeconds: 600
    resources:
      requests:
        memory: 2G
        cpu: 500m
      limits:
        memory: 2G
        cpu: 500m
    affinity:
      antiAffinityTopologyKey: "none"
    podDisruptionBudget:
      maxUnavailable: 1
    volumeSpec:
      persistentVolumeClaim:
        #        storageClassName: io1
        resources:
          requests:
            storage: 5G
    gracePeriod: 600
  haproxy:
    enabled: false
    size: 3
    image: percona/percona-xtradb-cluster-operator:1.11.0-haproxy
    readinessProbes:
      timeoutSeconds: 30
    livenessProbes:
      timeoutSeconds: 60
    serviceType: ClusterIP
#    replicasExternalTrafficPolicy: ClusterIP
    serviceAnnotations:
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    envVarsSecret: my-env-var-secrets
    resources:
      requests:
        memory: 2m
        cpu: 2m
    affinity:
      antiAffinityTopologyKey: "none"
    podDisruptionBudget:
      maxUnavailable: 1
    gracePeriod: 30
  proxysql:
    enabled: true
    pxchandler: scheduler
    size: 3
    image: perconalab/percona-xtradb-cluster-operator:proxysql-k8spxc-1071
    readinessDelaySec: 200
    livenessDelaySec: 600
    serviceType: ClusterIP
    serviceAnnotations:
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    externalTrafficPolicy: Cluster
    resources:
      requests:
        memory: 1G
        cpu: 100m
      limits:
        memory: 1G
        cpu: 100m
    affinity:
      antiAffinityTopologyKey: "none"
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 3G
    podDisruptionBudget:
      maxUnavailable: 1
    gracePeriod: 30
  logcollector:
    enabled: true
    image: perconalab/percona-xtradb-cluster-operator:main-logcollector
    resources:
      requests:
        memory: 100M
        cpu: 200m
  pmm:
    enabled: false
    image: percona/pmm-client:2.32.0
    serverHost: 3.73.128.178
    serverUser: admin
    pxcParams: "--disable-tablestats-limit=2000"
    resources:
      requests:
        memory: 400M
        cpu: 500m
  backup:
    image: perconalab/percona-xtradb-cluster-operator:main-pxc8.0-backup
    backoffLimit: 1
    pitr:
      enabled: false
      storageName: s3-pir
      timeBetweenUploads: 600
    storages:
      s3-pir:
        type: s3
        verifyTLS: true
        s3:
          bucket: mt-bucket-backup-tl/pir-test
          credentialsSecret: mt-cluster-1-backup-s3
          region: eu-west-3
      s3-ondemand:
        type: s3
        verifyTLS: true
        s3:
          bucket: mt-bucket-backup-tl/ondemand
          credentialsSecret: mt-cluster-1-backup-s3
          region: eu-west-3
      s3-eu-west: 
        type: s3
        verifyTLS: true
        s3:
          bucket: mt-bucket-backup-tl/scheduled-test
          credentialsSecret: mt-cluster-1-backup-s3
          region: eu-west-3
